[package]
name = "attr_mac"
version = "0.1.0"
authors = ["Freddy Wordingham <fjmw201@exeter.ac.uk>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc_mac = { path = "../proc_mac" }
proc-macro2 = "1.0.8"
quote = "1.0.2"
syn = { version = "1.0.13", features = ["full"] }
